server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          # http://localhost:3344/master/config-dev.yml即可访问
          uri: https://github.com/FLYQ-GIT/springcloud-config.git #GitHub上面的git仓库名字
#          default-label: master
          ####搜索目录
          search-paths:
            - springcloud-config
          skip-ssl-validation: true
          ####读取分支
      label: master
  #rabbitmq相关配置 15672是Web管理界面的端口；5672是MQ访问的端口
  rabbitmq:
    host: 192.168.0.130
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'