server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          # http://localhost:3344/master/config-dev.yml即可访问
          uri: https://github.com/FLYQ-GIT/springcloud-config.git #GitHub上面的git仓库名字
#          default-label: master
          ####搜索目录
          search-paths:
            - springcloud-config
          skip-ssl-validation: true
          ####读取分支
      label: master


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka