server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        # http://localhost:9527/payment/get/1 可以访问到http://localhost:8001/payment/get
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            - After=2020-07-03T22:50:40.933+08:00[Asia/Shanghai] # 特定时间之后可以访问，获取时间：ZonedDateTime now = ZonedDateTime.now();
#            - before=2020-07-03T22:50:40.933+08:00[Asia/Shanghai] # 特定时间之前可以访问
#            - between=2020-07-03T22:50:40.933+08:00[Asia/Shanghai] # 特定时间之间可以访问
            # curl http://localhost:9527/payment/get/2 --cookie "username=guocoffee" 使用curl命令访问
#            - Cookie=username,guocoffee # 需要携带cookie username为cookie的key,guocoffee为cookie的值
            # curl http://localhost:9527/payment/get/2 -H "X-Request-Id:11"
#            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            # curl http://localhost:9527/payment/get/2 -H "Host:news.guocoffee.com"
#            - Host=**.guocoffee.com
#            - Method=Get # 必须使用get请求
#            - Query=username,\d+ #必须含有username参数，且值必须为整数
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getClient         # 断言，路径相匹配的进行路由
#           https://cloud.spring.io/spring-cloud-gateway/2.2.x/reference/html/#gatewayfilter-factories
#           filters一些配置可以查看官网
#          filters:
#            - AddRequestHeader=X-Request-red, blue
        - id: payment_routh3 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/save         # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka