server:
  port: 7001

eureka:
  instance:
    hostname: eureka.com #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # 设置与eureka service交互的地址，查询服务和注册服务都需要依赖这个地址
      # http://eureka.com:7001/eureka/
      # 浏览器可以通过http://localhost:7001/访问eureka服务端
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      